FrontEnd/Models/PostsViewModel.cs
using Common.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace FrontEnd.Models
{
    public class PostsViewModel
    {
        public Post Post { get; set; }
        public Comment Comment { get; set; }
        public IEnumerable<Comment> Comments { get; set; }
    }
}

FrontEnd/Controllers/CommentsController.cs
using Common.Models;
using FrontEnd.Models;
using Managers.Managers;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FrontEnd.Controllers
{
    [Authorize]
    public class CommentsController : Controller
    {
        private readonly CommentManager _commentManager;

        public CommentsController(CommentManager commentManager)
        {
            _commentManager = commentManager;
        }

        [HttpPost]
        public ActionResult Create(SubmissionsViewModel vm)
        {
            vm.NewComment.UserId = User.Identity.GetUserId();
            vm.NewComment.UserName = User.Identity.GetUserName();

            vm.NewComment.SubmissionId = vm.Submission.Id;

            _commentManager.Create(vm.NewComment);

            return RedirectToAction("View", "Submissions", new { @id = vm.Submission.Id });
        }
    }
}

FrontEnd/Controllers/PostsController.cs
using Common.Models;
using FrontEnd.Models;
using Managers.Managers;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FrontEnd.Controllers
{
    public class PostsController : Controller
    {
        private readonly PostManager _postManager;
        private readonly CommentManager _commentManager;

        public PostsController(PostManager postManager, CommentManager commentManager)
        {
            _postManager = postManager;
            _commentManager = commentManager;
        }

        public ActionResult View(int id)
        {
            if (!_postManager.Exists(id))
            {
                return RedirectToAction("Index", "Home");
            }

            var vm = new PostsViewModel
            {
                Post = _postManager.Read(id),
                Comment = new Comment(),
                Comments = _commentManager.GetAllByPostId(id)
            };

            return View(vm);
        }

        public ActionResult Search(string searchTerm)
        {
            var list = _postManager.Search(searchTerm);

            return View(list);
        }

        [Authorize]
        public ActionResult Create()
        {
            Post post = new Post
            {
                UserId = User.Identity.GetUserId(),
                UserName = User.Identity.GetUserName()
            };

            return View(post);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Post post)
        {
            if (!ModelState.IsValid)
            {
                return View(post);    
            }

            int id = _postManager.Create(post);

            return RedirectToAction("View", new { @id = id });
        }
    }
}

FrontEnd/Views/Posts/Create.cshtml
@model Common.Models.Post

@{
    ViewBag.Title = "Create Post";
}

<h2>Create Post</h2>
@using (Html.BeginForm("Create", "Posts"))
{
    @Html.AntiForgeryToken()

    <div class="form-group">
        @Html.LabelFor(m => m.Title)
        @Html.TextBoxFor(m => m.Title, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Title, null, new { @class = "small text-danger"})
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Content)
        @Html.TextAreaFor(m => m.Content, new { @class = "form-control", @cols= 80, @rows = 10})
        @Html.ValidationMessageFor(m => m.Content, null, new { @class = "small text-danger" })
    </div>

    @Html.HiddenFor(m => m.UserId)
    @Html.HiddenFor(m => m.UserName)

    <a href="@Url.Action("Index", "Home")" class="btn btn-danger"><i class="fa fa-arrow-left"></i> Back</a>
    <button type="submit" class="btn btn-primary float-right"><i class="fa fa-plus"></i> Create Post</button>
}

FrontEnd/Views/Posts/Search.cshtml
@model IEnumerable<Common.Models.PostDetails>

@{
    ViewBag.Title = "Search";
}

<div class="row mt-3">
    <div class="col-sm-12">
        <h2>Search</h2>
        <ul class="list-group">
            @foreach (var item in Model)
            {
                @Html.Partial("~/Views/Posts/_PostBox.cshtml", item)
            }
        </ul>
    </div>
</div>

FrontEnd/Views/Posts/View.cshtml
@model FrontEnd.Models.PostsViewModel
<div class="row mb-4 mt-3">
    <div class="col-sm-12">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">@Model.Post.Title</h5>
                <p class="small text-muted mb-2">submitted @Model.Post.TimeStamp by @Model.Post.UserName</p>
                @Model.Post.Content
            </div>
            <div class="card-footer">
                @using (Html.BeginForm("Create", "Comments"))
                {
                    <div class="form-group">
                        @Html.TextAreaFor(m => m.Comment.Content, new { @class = "form-control" })
                    </div>

                    @Html.Hidden("Comment.PostId", Model.Post.Id)

                    <button type="submit" class="btn btn-primary">Reply</button>
                }

            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-sm-12">
        <h3>Comments</h3>
        <ul class="list-group">
            @foreach (var item in Model.Comments.Where(m => m.ParentCommentId == 0))
            {
                <li class="list-group-item">
                    <p class="text-success small mb-2">@item.UserName <span class="text-muted">@item.TimeStamp</span></p>
                    <p class="mb-2">@item.Content</p>
                    <p><a class="btn-reply small" href="#" data-comment-id="@item.Id">Reply</a></p>

                    <div class="reply-form" style="display: none;">
                        @using (Html.BeginForm("Create", "Comments"))
                        {
                            <div class="form-group">
                                @Html.TextAreaFor(m => m.Comment.Content, new { @class = "form-control", @id = "" })
                            </div>

                            @Html.Hidden("Comment.PostId", Model.Post.Id, new { @id = "" })
                            @Html.Hidden("Comment.ParentCommentId", item.Id, new { @id = "" })

                            <button type="submit" class="btn btn-primary btn-sm btn-save">Save</button>
                            <button class="btn btn-danger btn-sm btn-cancel">Cancel</button>
                        }
                    </div>

                </li>

                // Replys
                foreach(var item2 in Model.Comments.Where(m => m.ParentCommentId == item.Id))
                {
                    <li class="list-group-item ml-4">
                        <p class="text-success small mb-2">@item.UserName <span class="text-muted">@item.TimeStamp</span></p>
                        <p class="mb-2">RE: @item.Content</p>
                        <p><a class="btn-reply small" href="#" data-comment-id="@item.Id">Reply</a></p>
                    </li>
                }
            }
        </ul>
    </div>
</div>

@section Scripts 
{
    <script>
        $(document).ready(function () {
            $('.btn-reply').on('click', function (e) {
                e.preventDefault();

                var parent = $(e.target).closest('.list-group-item');
                var form = parent.find('.reply-form');

                form.toggle('drop', 750);
            });

            $('.btn-cancel').on('click', function (e) {
                e.preventDefault();

                var parent = $(e.target).closest('.list-group-item');
                var form = parent.find('.reply-form');

                form.toggle('drop', 750);
            });
        });
    </script>
}