FrontEnd/Models/HomeViewModel.cs
using Common.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace FrontEnd.Models
{
    public class HomeViewModel
    {
        public IEnumerable<SubmissionDetails> Submissions { get; set; }
        public int PageNumber { get; set; }
        public int PageCount { get; set; }
        public SortType SortType { get; set; }
    }
}

FrontEnd/Controllers/HomeController.cs
using Common.Models;
using FrontEnd.Models;
using Managers.Managers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FrontEnd.Controllers
{
    public class HomeController : Controller
    {
        private readonly SubmissionManager _submissionManager;

        public HomeController(SubmissionManager submissionManager)
        {
            _submissionManager = submissionManager;
        }

        public ActionResult Index(int page = 1, int numPerPage = 5, SortType sort = SortType.Date)
        {
            var vm = new HomeViewModel();

            double total = _submissionManager.GetTotalCount();
            int pageCount = (int)Math.Ceiling(total / numPerPage);
            vm.Submissions = _submissionManager.GetPaged(page, numPerPage, sort);
            vm.PageNumber = page;
            vm.PageCount = pageCount;
            vm.SortType = sort;

            return View(vm);
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

FrontEnd/Controllers/SubmissionsController.cs
using Common.Models;
using FrontEnd.Models;
using Managers.Managers;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace FrontEnd.Controllers
{
    public class SubmissionsController : Controller
    {
        private readonly SubmissionManager _submissionManager;
        private readonly CommentManager _commentManager;
        private readonly SubmissionVoteManager _submissionVoteManager;

        public SubmissionsController(SubmissionManager submissionManager, CommentManager commentManager, SubmissionVoteManager submissionVoteManager)
        {
            _submissionManager = submissionManager;
            _commentManager = commentManager;
            _submissionVoteManager = submissionVoteManager;
        }

        public ActionResult View(int id)
        {
            if (!_submissionManager.Exists(id))
            {
                return RedirectToAction("Index", "Home");
            }

            var vm = new SubmissionsViewModel
            {
                Submission = _submissionManager.Read(id),
                NewComment = new Comment(),
                Comments = _commentManager.GetAllBySubmissionId(id)
            };

            return View(vm);
        }

        public ActionResult Search(string searchTerm)
        {
            var vm = new SearchSubmissionViewModel
            {
                SearchResults = _submissionManager.Search(searchTerm),
                SearchTerm = searchTerm
            };

            return View(vm);
        }

        [Authorize]
        public ActionResult Create(SubmissionType type = SubmissionType.Text)
        {
            var vm = new CreateSubmissionViewModel
            {
                Submission = new Submission
                {
                    UserId = User.Identity.GetUserId(),
                    UserName = User.Identity.GetUserName()
                },
                Type = type
            };

            return View(vm);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CreateSubmissionViewModel vm)
        {
            vm.Submission.Type = vm.Type;

            if (vm.Type == SubmissionType.Link)
            {
                if (String.IsNullOrWhiteSpace(vm.Submission.URL))
                {
                    ModelState.AddModelError("Submission.URL", "Please enter a URL.");
                }
                else
                {
                    if (!Uri.IsWellFormedUriString(vm.Submission.URL, UriKind.Absolute))
                    {
                        ModelState.AddModelError("Submission.URL", "Please enter a valid URL.");
                    }
                }
            }
            else
            {
                if (String.IsNullOrEmpty(vm.Submission.Content))
                {
                    ModelState.AddModelError("Submission.Content", "Please enter some content.");
                }
            }

            if (!ModelState.IsValid)
            {
                return View(vm);    
            }

            int id = _submissionManager.Create(vm.Submission);

            return RedirectToAction("View", new { @id = id });
        }

        public PartialViewResult VoteButtons(int submissionId)
        {
            string userId = User.Identity.GetUserId();

            VoteButtons voteButtons = new VoteButtons
            {
                Score = _submissionManager.GetScore(submissionId),
                UserVoteType = _submissionVoteManager.GetUserVote(submissionId, userId)
            };

            return PartialView("_VoteButtons", voteButtons);
        }

        public ActionResult UserSubmissions(string userId)
        {
            var vm = new UserSubmissionsViewModel
            {
                Submissions = _submissionManager.GetSubmissionsByUserId(userId),
                UserName = HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>().FindById(userId).UserName
            };
            
            return View(vm);
        }

        [Authorize]
        [HttpPost]
        public JsonResult UpVote(int id)
        {
            string userId = User.Identity.GetUserId();

            if (!_submissionVoteManager.HasUserVoted(id, userId))
            {
                _submissionManager.UpVote(id);
                _submissionVoteManager.UpVote(id, userId);
            }

            return Json(_submissionManager.GetScore(id), JsonRequestBehavior.AllowGet);
        }

        [Authorize]
        [HttpPost]
        public JsonResult DownVote(int id)
        {
            string userId = User.Identity.GetUserId();

            if (!_submissionVoteManager.HasUserVoted(id, userId))
            {
                _submissionManager.DownVote(id);
                _submissionVoteManager.DownVote(id, userId);
            }

            return Json(_submissionManager.GetScore(id), JsonRequestBehavior.AllowGet);
        }
    }
}

FrontEnd/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

FrontEnd/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

FrontEnd/Views/Home/Index.cshtml
@model FrontEnd.Models.HomeViewModel
@{
    ViewBag.Title = "Home Page";
}

<div class="row mt-3 d-md-none">
    <div class="col-12">
        @using (Html.BeginForm("Search", "Submissions", FormMethod.Get))
        {
            <div class="input-group">
                <input type="text" class="form-control" name="searchTerm" placeholder="Search...">
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="submit"><i class="fa fa-search"></i></button>
                </div>
            </div>
        }
    </div>
</div>

<div class="row mt-3">
    <div class="col-md-7 col-lg-9">
        <div class="mb-2">
            <span class="small">Sort by: </span>
            <div class="btn-group" role="group" aria-label="Basic example">
                <a href="@Url.Action("Index", "Home", new { @page = Model.PageNumber, @sort = Common.Models.SortType.Date })" class="btn @(Model.SortType == Common.Models.SortType.Date ? "btn-primary" : "btn-light") btn-sm">Date</a>
                <a href="@Url.Action("Index", "Home", new { @page = Model.PageNumber, @sort = Common.Models.SortType.Score })" class="btn @(Model.SortType == Common.Models.SortType.Score ? "btn-primary" : "btn-light") btn-sm">Score</a>
            </div>
        </div>
        
        <ul class="list-group">
            @foreach (var item in Model.Submissions)
            {
                @Html.Partial("~/Views/Submissions/_SubmissionBox.cshtml", item)
            }
        </ul>
    </div>
    <div class="col-md-5 col-lg-3 d-none d-md-block d-lg-block d-xl-block">
        <div class="card">
            <div class="card-body">
                @using (Html.BeginForm("Search", "Submissions", FormMethod.Get))
                {
                    <div class="input-group mb-3">
                        <input type="text" class="form-control" name="searchTerm" placeholder="Search...">
                        <div class="input-group-append">
                            <button class="btn btn-outline-secondary" type="submit"><i class="fa fa-search"></i></button>
                        </div>
                    </div>
                }

                <p><a class="btn btn-primary btn-block" href="@Url.Action("Create", "Submissions", new { @type = Common.Models.SubmissionType.Text })">Create New Text Submission</a></p>
                <p><a class="btn btn-primary btn-block" href="@Url.Action("Create", "Submissions", new { @type = Common.Models.SubmissionType.Link })">Create New Link Submission</a></p>
            </div>
        </div>
    </div>
</div>

<div class="row mt-3">
    <div class="col-sm-12">
        @Html.Partial("~/Views/Submissions/_Navigation.cshtml", Model)
    </div>
</div>